# Exercises on Benders Algorithm

## Task 1

Write an extended formulation with extreme points and extreme rays for the polyhedron

$$
\begin{align*}
−x_1 +x_2 &\leq 1\\
3x_1 +x_2 &\geq 5 \\
x_1 +x_2  &\geq 1\\
x_1 +2x_2 &\leq 11.
\end{align*}
$$

![plot](./lpsolve.png)

The two points where there are rays are $[3,4]$ and $[2,-1]$. 
The point $[3,4]$ is the intersection of 

$$
\begin{array}{ll}
-x + y  &=  1\\
x + 2y  &=  11
\end{array}
$$

and the ray is given by the line $x + 2y  =  11$. Rewriting in vector form:

$$
\begin{bmatrix}
x\\
11/2- 1/2x
\end{bmatrix}
=
\begin{bmatrix}
0\\
11/2
\end{bmatrix}
x\begin{bmatrix}
1\\
-1/2
\end{bmatrix}
$$


The point $[2,-1]$ is the intersection of 

$$
\begin{array}{ll}
3x + y &= 5\\
x + y &= 1
\end{array}
$$

and the ray is given by the line $x + y  =  1$. Rewriting in vector form:

$$
\begin{bmatrix}
x\\
1- x
\end{bmatrix}
=
\begin{bmatrix}
0\\
1
\end{bmatrix}
x\begin{bmatrix}
1\\
-1
\end{bmatrix}
$$

Hence, the extended formulation is:

$$
X=\left\{x \mid \begin{array}{ll}
x = &\lambda_1 \begin{bmatrix}3\\4\end{bmatrix}+\lambda_2 \begin{bmatrix}2\\-1\end{bmatrix}+\lambda_3 \begin{bmatrix}1\\2\end{bmatrix}+\delta_1\begin{bmatrix}1\\-1/2\end{bmatrix}+\delta_2\begin{bmatrix}
1\\-1\end{bmatrix},\\
&\lambda_1,\lambda_2,\lambda_3\geq 0,\\
&\lambda_1+\lambda_2+\lambda_3=1,\\
&\delta_1,\delta_2,\geq 0 \}
\end{array}
\right\}
$$


## Task 2

Consider the mixed integer program 

$$
\begin{align}
\max\; &4x_1 +5x_2 +2y_1 −7y_2 +5y_3 \\
&3x_1 +4x_2 +2y_1 −2y_2 +3y_3\leq 10\\
&\vec x\leq 3,\; \vec x\in \mathbb{Z}^2_+,\; \vec y\leq 2,\; \vec y\in \mathbb{R}^3_+. 
\end{align}
$$

Solve it using Benders’ algorithm.

After solving it, you are informed that the $y$ variables should also be integer.
Without starting again from scratch:
1. Solve the new problem using a basic branch and bound algorithm (Section 12.5.1)
2. Solve using no-good cuts.


# Solution
We can rewrite the problem in the same matrix terms as seen in the lecture:
$$
\begin{align}
\max \;& \vec{c}^T\vec{x}+\vec{h}^T\vec{y}\\
&F\vec{x}+G\vec{y}\leq \vec{d}\\
&\vec{x}\in X \cap \mathbb{Z}^q_+ \; \vec{y}\in \mathbb{R}^p_+
\end{align}
$$
which in our case becomes:
$$
\begin{align}
\max\; &\begin{bmatrix}4& 5\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix} + \begin{bmatrix}2&-7&5\end{bmatrix}\begin{bmatrix}y_1 \\y_2\\y_3\end{bmatrix} \\
&\begin{bmatrix}3&4\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix} +\begin{bmatrix}2&-2&3\end{bmatrix}\begin{bmatrix}y_1\\y_2\\y_3\end{bmatrix}\leq 10\\
&\begin{bmatrix}1&0\\0&1\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}+\begin{bmatrix}0&0&0\\0&0&0\end{bmatrix}\begin{bmatrix}y_1\\y_2\\y_3\end{bmatrix}\leq \begin{bmatrix}3\\3\end{bmatrix}\\
&\begin{bmatrix}0&0\\0&0\\0&0\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}+\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}\begin{bmatrix}y_1\\y_2\\y_3\end{bmatrix}\leq \begin{bmatrix}2\\2\\2\end{bmatrix}\\
&\vec x\in \mathbb{Z}^2_+,\; \vec y\in \mathbb{R}^3_+. 
\end{align}
$$

We will need to use duality theory in the subproblem so we decide to fix the $x$ variables thus leaving the subproblem a linear programming problem. For a fixed $x=\bar{x}$ we get the Benders subproblem:
$$
\begin{align}
\max\; & +2y_1 −7y_2 +5y_3\\
&2{y}_1-2{y}_2+3{y}_3\leq 10-3\bar{x}_1 -4\bar{x}_2\\
&\vec y\leq 2,\; \vec y\in \mathbb{R}^3_+. 
\end{align}
$$

Next, in some variables $u_1,u_2,u_3,u_4$ we derive the dual of the subproblem (DSP):
$$
\begin{align}
\min\; &(10-3\bar{x}_1 -4\bar{x}_2)u_1+2u_2+2u_3+2u_4 \\
&2u_1+u_2\geq 2\\
&-2u_1+u_3\geq -7\\
&3u_1+u_4\geq 5\\
&\vec u\in \mathbb{R}^4_+ 
\end{align}
$$

The Benders reformulation (BR), aka extensive formulation (EF), in the extreme rays $v^r, r \in R$ and extreme points $w^p, p \in P$ of $\vec{u}^TG\leq d$ is:
$$
\begin{align}
z^*=\max\; &4x_1 +5x_2 + \eta \\
&v^r(10-3x_1-4x_2) \geq 0 &\forall r \in R\\
&w^p(10-3x_1-4x_2) \geq \eta &\forall p \in P\\
&\vec x\leq 3,\; \vec x\in \mathbb{Z}^2_+,\; \eta \in \mathbb{R}^1.                                  
\end{align}
$$

We start the Benders' algorithm by relaxing the integrality constraint on the $\vec{x}$ variables and removing all feasibility and optimality constraints yeilding a reduced extensive formulation (REF): 
$$
\begin{align}
z^*=\max\; &4x_1 +5x_2 + \eta \\
&\vec x\leq 3,\; \eta \in \mathbb{R}^1.                                  
\end{align}
$$

The optimal solution of the current (REF) is trivial: $z^*=+\infty$, $\eta^*=+\infty$ and $\vec{x}^*=[3,3]$.  

In [18]:
import numpy as np
import scipy.optimize as opt

c = np.array([4,5])
h = np.array([2,-7,5])
F = np.concatenate((np.array([[3,4]]),np.eye(2),np.zeros((3,2))),axis=0)
G = np.concatenate((np.array([[2,-2,3]]),np.zeros((2,3)),np.eye(3)),axis=0)
d = np.array([10,3,3,2,2,2])

x_star=np.array([3,3])
print(F,G)

constraints = opt.LinearConstraint(A=np.concatenate([F,G],axis=1), lb=0, ub=d)
integrality=np.array([1,1,0,0,0])
bounds = opt.Bounds(lb=np.zeros(5), ub=np.array([3,3,2,2,2]))
values=np.concatenate([c,h],axis=0)
res = opt.milp(c=-values, constraints=constraints, integrality=integrality, bounds=bounds, options={'disp': True})
print(res)


[[3. 4.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] [[ 2. -2.  3.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -15.0
              x: [ 1.000e+00  0.000e+00  5.000e-01  0.000e+00  2.000e+00]
 mip_node_count: 1
 mip_dual_bound: -15.0
        mip_gap: 0.0
Running HiGHS 1.2.0 [date: 2021-07-09, git hash: n/a]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Presolving model
1 rows, 5 cols, 5 nonzeros
1 rows, 5 cols, 5 nonzeros

Solving MIP model with:
   1 rows
   5 cols (0 binary, 2 integer, 0 implied int., 3 continuous)
   5 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00% 

In [19]:
import gurobipy as gp

def solve_DSP(d,h,F,G,xstar,silent=False):
    # Model
    m = gp.Model("DSP")
    m.setParam(gp.GRB.Param.InfUnbdInfo, 1)
    if silent:
        m.setParam(gp.GRB.Param.OutputFlag, 0)
    
    # Create variables
    u = m.addMVar(shape=G.shape[0], vtype=gp.GRB.CONTINUOUS, name="u")

    # Set objective
    m.setObjective(u @ (d-F @ xstar), gp.GRB.MINIMIZE)

    # Add constraints
    m.addConstr(G.T @ u>= h, name="c")
    if not silent: 
        m.update()
        m.display()
    # Optimize model
    m.optimize()
    return m, u

In [20]:
dsp_model, dsp_sol = solve_DSP(d,h,F,G,x_star)

if dsp_model.status == gp.GRB.status.INFEASIBLE:
    print("Instance infeasible")
elif dsp_model.status == gp.GRB.status.OPTIMAL:
    print("extreme point:", dsp_sol.X)
elif dsp_model.status == gp.GRB.status.UNBOUNDED:
    print("extreme ray:",dsp_sol.UnbdRay)

Set parameter InfUnbdInfo to value 1
Minimize
  -11.0 u[0] + 2.0 u[3] + 2.0 u[4] + 2.0 u[5]
Subject To
  c[0]: 2.0 u[0] + u[3] >= 2
  c[1]: -2.0 u[0] + u[4] >= -7
  c[2]: 3.0 u[0] + u[5] >= 5
Gurobi Optimizer version 12.0.0 build v12.0.0rc1 (mac64[arm] - Darwin 24.4.0 24E263)

CPU model: Apple M1 Max
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads

Non-default parameters:
InfUnbdInfo  1

Optimize a model with 3 rows, 6 columns and 6 nonzeros
Model fingerprint: 0x3485e092
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [2e+00, 1e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+00, 7e+00]
Presolve removed 0 rows and 2 columns
Presolve time: 0.00s
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -1.1000000e+31   1.000000e+30   1.100000e+01      0s

Solved in 2 iterations and 0.00 seconds (0.00 work units)
Unbounded model
extreme ray: [0.5 0.  0.  0.  1.  0. ]


/var/folders/2d/8kc387tn67v4tc9_8t9d2myr0000gq/T/ipykernel_96296/550583442.py:20: DeprecationWarning: Model.display() is deprecated
  m.display()


We find a ray and a feasibility constraint that is currently violated in the Benders reformulation: $v^r(d-Fx^*) < 0$

In [21]:
dsp_sol.UnbdRay @ (d-F @ x_star)

np.float64(-3.5)

We need to add the feasibility cut $(u^r)^T(d-Fx)\geq 0$:
$$
\begin{bmatrix}0.5&0&0&0&&1&0\end{bmatrix}\left(\begin{bmatrix}10\\3\\3\\2\\2\\2\end{bmatrix}-\begin{bmatrix}3&4\\1&0\\0&1\\0&0\\0&0\\0&0\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}\right)\geq 0
$$
that is:
$$
\begin{bmatrix}0.5&0&0&0&&1&0\end{bmatrix}\left(\begin{bmatrix}10\\3\\3\\2\\2\\2\end{bmatrix}-\begin{bmatrix}3x_1+4x_2\\x_1\\x_2\\0\\0\\0\end{bmatrix}\right)\geq 0
$$
$$
\begin{bmatrix}0.5&0&0&0&&1&0\end{bmatrix}\begin{bmatrix}10-3x_1-4x_2\\3-x_1\\3-x_2\\2\\2\\2\end{bmatrix}\geq 0
$$
$$
7-1.5x_1-2x_2\geq 0
$$
$$
3x_1+4x_2\leq 14
$$

In [22]:
def solve_REF(c,d,F,extreme_rays=[], extreme_points=[], silent=False):
     # Model
    m = gp.Model("DSP")
    m.setParam(gp.GRB.Param.DualReductions, 0)
    if silent:
        m.setParam(gp.GRB.Param.OutputFlag, 0)

    # Create variables
    x = m.addMVar(shape=F.shape[1], ub=3, vtype=gp.GRB.INTEGER, name="x")
    eta = m.addMVar(shape=1, ub=100, vtype=gp.GRB.CONTINUOUS, name="eta")

    # Set objective
    m.setObjective(c @ x + eta, gp.GRB.MAXIMIZE)

    # Add constraints
    for ray in extreme_rays:
        m.addConstr(ray @ (d - F @ x)>=0, name="feasibility cut")
    for point in extreme_points:
        m.addConstr(point @ (d - F @ x)>=eta, name="optimality cut")
    if not silent:
        m.update()
        m.display()
    # Optimize model
    m.optimize()
    return m,x,eta

In [23]:
ref_model, ref_sol_x, ref_sol_eta = solve_REF(c,d,F, [dsp_sol.UnbdRay])

Set parameter DualReductions to value 0
Maximize
  4.0 x[0] + 5.0 x[1] + eta[0]
Subject To
  feasibility cut: -1.5 x[0] + -2.0 x[1] >= -7
Bounds
  -0 <= x[0] <= 3
  -0 <= x[1] <= 3
  0 <= eta[0] <= 100
General Integers
  ['x[0]', 'x[1]']
Gurobi Optimizer version 12.0.0 build v12.0.0rc1 (mac64[arm] - Darwin 24.4.0 24E263)

CPU model: Apple M1 Max
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads

Non-default parameters:
DualReductions  0

Optimize a model with 1 rows, 3 columns and 2 nonzeros
Model fingerprint: 0xc967af30
Variable types: 1 continuous, 2 integer (0 binary)
Coefficient statistics:
  Matrix range     [2e+00, 2e+00]
  Objective range  [1e+00, 5e+00]
  Bounds range     [3e+00, 1e+02]
  RHS range        [7e+00, 7e+00]
Found heuristic solution: objective 117.0000000
Presolve time: 0.00s
Presolved: 1 rows, 3 columns, 2 nonzeros
Variable types: 1 continuous, 2 integer (0 binary)

Root relaxation: objective 1.182500e+02, 1 iterations, 0.00 seconds (0.

/var/folders/2d/8kc387tn67v4tc9_8t9d2myr0000gq/T/ipykernel_96296/3273254003.py:22: DeprecationWarning: Model.display() is deprecated
  m.display()


We can now write the overall procedure to solve the linear relaxation of the original problem.

In [24]:
extreme_rays=[]
extreme_points=[]
while True:
    # We solve the Restricted Benders reformulation (RBR) or restricted extended formulation:
    ref_model, ref_sol_x, ref_sol_eta = solve_REF(c,d,F,extreme_rays, extreme_points,silent=True)
    if ref_model.status == gp.GRB.status.INFEASIBLE:
        print("Instance infeaasible")
        break
    elif ref_model.status == gp.GRB.status.UNBOUNDED:
        print("Ref unbounded:",ref_sol_x.X,ref_sol_eta.X)        
        break
    elif ref_model.status == gp.GRB.status.OPTIMAL:
        print("REF solution",ref_sol_x.X,ref_sol_eta.X)
    else:
        print('Optimization was stopped with status %d' % m.status)
        break
    # We solve the Dual Subproblem
    dsp_model, dsp_sol = solve_DSP(d,h,F,G,ref_sol_x.X, silent=True)
    if dsp_model.status == gp.GRB.status.UNBOUNDED:
        print("Found extreme ray:",dsp_sol.UnbdRay)
        extreme_rays=extreme_rays+[dsp_sol.UnbdRay]
    elif dsp_model.status == gp.GRB.status.OPTIMAL:
        print("Found extreme point:", dsp_sol.X)
        if dsp_model.objVal < ref_sol_eta.X:
            extreme_points=extreme_points+[dsp_sol.X]
        elif dsp_model.objVal == ref_sol_eta.X:
            print("Problem Solved: ",
                  f"z={ref_model.objVal}, eta={ref_sol_eta.X},"
                  f"x={ref_sol_x.X}, y={[c.Pi for c in dsp_model.getConstrs()]}")
            break
    elif dsp_model.status == gp.GRB.status.INFEASIBLE:
        print("DSP Instance infeaasible")
        break

Set parameter DualReductions to value 0
REF solution [3. 3.] [100.]
Set parameter InfUnbdInfo to value 1
Found extreme ray: [0.5 0.  0.  0.  1.  0. ]
Set parameter DualReductions to value 0
REF solution [2. 2.] [100.]
Set parameter InfUnbdInfo to value 1
Found extreme point: [3.5 0.  0.  0.  0.  0. ]
Set parameter DualReductions to value 0
REF solution [-0. -0.] [35.]
Set parameter InfUnbdInfo to value 1
Found extreme point: [0. 0. 0. 2. 0. 5.]
Set parameter DualReductions to value 0
REF solution [ 2. -0.] [14.]
Set parameter InfUnbdInfo to value 1
Found extreme point: [1.66666667 0.         0.         0.         0.         0.        ]
Set parameter DualReductions to value 0
REF solution [1. 0.] [11.66666667]
Set parameter InfUnbdInfo to value 1
Found extreme point: [1. 0. 0. 0. 0. 2.]
Set parameter DualReductions to value 0
REF solution [1. 0.] [11.]
Set parameter InfUnbdInfo to value 1
Found extreme point: [1. 0. 0. 0. 0. 2.]
Problem Solved:  z=15.0, eta=[11.],x=[1. 0.], y=[0.5, 0.0,